<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pedidosbtnFlechaParaBaixoCliente</name>
   <tag></tag>
   <elementGuidId>ccc286ae-07a3-48dc-94b8-be1419294e0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//thf-combo[@id='entidadeId']/thf-field-container/div/div[2]/div/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;entidadeId&quot;)/thf-field-container[1]/div[@class=&quot;thf-field-container&quot;]/div[@class=&quot;thf-field-container-content&quot;]/div[@class=&quot;thf-field-icon-container-right&quot;]/span[@class=&quot;thf-icon thf-field-icon thf-icon-arrow-down&quot;][count(. | //*[@class = 'thf-icon thf-field-icon thf-icon-arrow-down']) = count(//*[@class = 'thf-icon thf-field-icon thf-icon-arrow-down'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>thf-icon thf-field-icon thf-icon-arrow-down</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;entidadeId&quot;)/thf-field-container[1]/div[@class=&quot;thf-field-container&quot;]/div[@class=&quot;thf-field-container-content&quot;]/div[@class=&quot;thf-field-icon-container-right&quot;]/span[@class=&quot;thf-icon thf-field-icon thf-icon-arrow-down&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//thf-combo[@id='entidadeId']/thf-field-container/div/div[2]/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/thf-combo/thf-field-container/div/div[2]/div/span</value>
   </webElementXpaths>
</WebElementEntity>
