<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>listagemPedidosJanelabtnX</name>
   <tag></tag>
   <elementGuidId>b5ec499b-89ab-4b7d-8e63-3f0a946ba5a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>thf-icon thf-icon-close</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;thf-wrapper&quot;]/app-pedidos[1]/thf-page-default[1]/thf-page[1]/div[@class=&quot;thf-page&quot;]/thf-page-content[1]/div[@class=&quot;thf-page-content&quot;]/div[@class=&quot;thf-xl-12 thf-lg-12 thf-md-12 thf-sm-12 form-container&quot;]/thf-modal[1]/div[@class=&quot;thf-modal&quot;]/div[@class=&quot;thf-modal-overlay&quot;]/div[@class=&quot;thf-modal-container thf-pb-2 thf-pt-2&quot;]/div[@class=&quot;thf-modal-vertical-align&quot;]/div[@class=&quot;thf-modal-content thf-modal-md&quot;]/div[@class=&quot;thf-modal-header&quot;]/a[@class=&quot;thf-modal-header-close-button&quot;]/span[@class=&quot;thf-icon thf-icon-close&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
   </webElementXpaths>
</WebElementEntity>
