<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>listagemClientesGridIdentificacaoCPF</name>
   <tag></tag>
   <elementGuidId>107e15df-4046-4f97-bf98-5b57bdb0df27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;tableClientes&quot;]/thf-container/div/div/div/div/div/table/tbody/tr/td[2]/div/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
