<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clientesRetornoCEP</name>
   <tag></tag>
   <elementGuidId>1727e414-7d2c-4e36-96b4-0ecc406d5d97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//thf-input[@id='cep']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
