<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clientesRetornoCPF</name>
   <tag></tag>
   <elementGuidId>b01e265d-9c87-4b04-9aba-0f06b7c55e5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;cpf&quot;]/thf-field-container/div/div[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//thf-input[@id='cpf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;cpf&quot;]/thf-field-container/div/div[2]</value>
   </webElementProperties>
</WebElementEntity>
