<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clientesRetornoTelefone</name>
   <tag></tag>
   <elementGuidId>f03c13e0-1890-4f00-b3aa-b9fb0ffd0796</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//thf-input[@id='telefone']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
